export const SET_CURRENCY = 'SET_CURRENCY';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const INCREASE_QUANTITY_ORDER = 'INCREASE_QUANTITY_ORDER';
export const DECREASE_QUANTITY_ORDER = 'DECREASE_QUANTITY_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';
